version: '3.7'

services:

  postgres:
    build: docker/postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /volumes/postgres13/data:/var/lib/postgresql/data:rw
    env_file:
      - docker/postgres/postgres.env
  fastapi1:
    build: .
    container_name: fastapi1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '3GB'
    ports:
      - 8080:8080
  fastapi2:
    build: .
    container_name: fastapi2
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: '3GB'
    ports:
      - 8082:8080
  redis:
    image: redis:latest
    container_name: redis
  nginx:
    image: openresty/openresty
    container_name: nginx
    restart: "always"
    ports:
      - 80:80
    volumes:
      - /volumes/nginx/html:/usr/share/nginx/html:rw
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./docker/nginx/nginx.conf
        target: /etc/openresty/nginx.conf
    environment:
      TZ: TZ=America/Fortaleza